# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
cmake_target_version: "3.13.1"
clang_target_version: "7.1.0"
esy_target_version: "0.5.8"
shellcheck_target_version: "0.4.6"
cmake_prefix: "/usr/local"
esy_prefix: "/usr/local/lib/esy"
esy_bin_prefix: "/usr/local/bin"

clang_binary_name: "clang-7"

apt_packages:
  - "curl"
  - "clang-7"
  - "clang-format-7"
  - "make"
  - "ninja-build"
  - "shellcheck"
  - "gcc"
  - "g++"
  - "gdb"
  - "lcov"
  - "libssl-dev"
  - "openssl"
  - "pkg-config"
  - "python-pip"
  - "apt-transport-https"
  - "autoconf"
  - "doxygen"
  - "graphviz"
  - "libexpat1-dev"
  - "libtool"
  - "subversion"
  - "libcurl4-openssl-dev"
  - "libx11-dev"
  - "libncurses5-dev"

apt_arm_packages:
  - "gcc-arm-linux-gnueabi"
  - "gcc-arm-linux-gnueabihf"
  - "gcc-aarch64-linux-gnu"
  - "g++-aarch64-linux-gnu"
  - "python-crypto"
  - "libc6-dev:arm64"
  - "libssl-dev:arm64"
  - "libfdt1"
  - "openssh-client"
  - "sshpass"

pip_packages:
  - "lcov_cobertura"

validation_distribution_binaries:
  - "/usr/bin/shellcheck"
  - "/usr/bin/clang-7"

validation_distribution_files:
  - "/usr/lib/x86_64-linux-gnu/libssl.so"
